project_id = "pmqkclhqvjfmcxzuoypa"

[functions.send-push-notification]
verify_jwt = false

[functions.notify-rider]
verify_jwt = false

[functions.create-order-api]
verify_jwt = false

[functions.assign-rider-api]
verify_jwt = false

[functions.calculate-distance]
verify_jwt = false

[functions.get-firebase-config]
verify_jwt = false

[functions.send-delivery-push]
verify_jwt = false